server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql-db2:3306/pheobus?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Penelope01
  jpa:
    hibernate:
      ddl-auto: create-drop
